# Generated by Django 5.1.1 on 2024-09-20 15:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TestGroup",
            fields=[
                ("test_group_id", models.AutoField(primary_key=True, serialize=False)),
                ("test_group_name", models.CharField(max_length=255)),
                (
                    "weight",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ]
                    ),
                ),
            ],
        ),
    ]
