# Generated by Django 5.1.1 on 2024-09-15 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StudentPerformance",
            fields=[
                ("performance_id", models.AutoField(primary_key=True, serialize=False)),
                ("user_id", models.IntegerField()),
                ("course_id", models.IntegerField()),
                ("quiz_id", models.IntegerField(blank=True, null=True)),
                ("assignment_id", models.IntegerField(blank=True, null=True)),
                ("score", models.DecimalField(decimal_places=2, max_digits=5)),
                ("feedback", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
