# Generated by Django 5.1.1 on 2024-09-23 03:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student_performance", "0001_initial"),
        ("test_group", "0002_alter_testgroup_test_group_name_test"),
        ("user", "0006_alter_user_user_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studentperformance",
            name="assignment_id",
        ),
        migrations.RemoveField(
            model_name="studentperformance",
            name="course_id",
        ),
        migrations.RemoveField(
            model_name="studentperformance",
            name="quiz_id",
        ),
        migrations.AddField(
            model_name="studentperformance",
            name="test_id",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="test_group.test",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="studentperformance",
            name="user_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="user.user"
            ),
        ),
    ]
