# Generated by Django 5.1.1 on 2024-09-23 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "student_performance",
            "0002_remove_studentperformance_assignment_id_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="studentperformance",
            old_name="test_id",
            new_name="test",
        ),
        migrations.RenameField(
            model_name="studentperformance",
            old_name="user_id",
            new_name="user",
        ),
    ]
