# Generated by Django 5.1.1 on 2024-09-19 04:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "course_code",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("course_name", models.CharField(max_length=255)),
                ("course_description", models.TextField(blank=True, null=True)),
                ("created_by", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
