# Generated by Django 5.1.1 on 2024-09-20 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0003_alter_course_created_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="course",
            old_name="course_code",
            new_name="course_id",
        ),
    ]
