# Generated by Django 5.1.1 on 2024-09-20 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0004_rename_course_code_course_course_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="course_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
