# Generated by Django 5.1.1 on 2024-09-23 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("performance_analytic", "0001_initial"),
        ("user", "0006_alter_user_user_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="PerformanceAnalytic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("course_id", models.IntegerField()),
                ("total_score", models.DecimalField(decimal_places=2, max_digits=10)),
                ("progress", models.DecimalField(decimal_places=2, max_digits=10)),
                ("last_accessed", models.DateTimeField(auto_now=True)),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="user.user"
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="UserProgress",
        ),
    ]
