# Generated by Django 5.1.1 on 2024-09-23 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0005_alter_course_course_id"),
        ("performance_analytic", "0002_performanceanalytic_delete_userprogress"),
    ]

    operations = [
        migrations.RenameField(
            model_name="performanceanalytic",
            old_name="user_id",
            new_name="user",
        ),
        migrations.RemoveField(
            model_name="performanceanalytic",
            name="course_id",
        ),
        migrations.AddField(
            model_name="performanceanalytic",
            name="course",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="course.course",
            ),
            preserve_default=False,
        ),
    ]
