# Generated by Django 5.1.1 on 2024-09-19 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_remove_user_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_id",
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
